### ISSUE TITLE
How to deploy this code?

### ISSUE THREAD

**Issue by Valaia** [niwacode/quickfingersscanner#1]
I'm sorry for writing this here, I realize it's not a real issue. But how can I use this code? I tried deploying using Heroku but it doesn't work. I'm a noob when it comes to this, can someone please direct me in the right direction ? Thank you!

**Comment by Valaia** [comment]
I figured out that I need a Slack api key... How do I even get that? I tried joining the Quickfingers traders slack group but I couldn't. Any solutions?.. please?

**Comment by jspdown** [comment]
@Valaia To make it works you have to follow these steps:
- Create a Slack workspace
- Generate a token using the legacy token generator: https://api.slack.com/custom-integrations/legacy-tokens
- Create the following channels:
  - scanner_alerts_fiat
  - scanner_alerts_btc
  - scanner_alerts_eth
- Close this repository
- Install typescript `npm install -g tsc`
- Transpile ts files into js files: `tsc *.ts`
- Run the scanner: `node index.js`
- Enable slack notification: `slack true`
- Add your slack token: `slackkey <your-token>`
- Save the configuration: `save`

**Comment by bausan** [comment]
Can you help me with this?

I followed your step and get this error when in run node index.js

node index.js
module.js:540
    throw err;
    ^

Error: Cannot find module '@slack/client'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\.....\github\quickfingersscanner\slack.js:1:79)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
